config/routes.rb
MhmrTroubleshooter::Application.routes.draw do
  resources :emails do
   collection do
	get 'deleted'
	end
   member do
	get 'restore'
	end
  end
  devise_for :users, :path_prefix => 'mhmr'
  resources :categories do
   collection do
	get 'deleted'
	end
   member do
	get 'restore'
   end
  end
  resources :tickets do
   collection do
	get 'summary'
	post 'summary'
	get 'monthSummary'
	end
  end
  resources :locations do
   collection do
	get 'deleted'
	end
   member do
	get 'restore'
	end
   end
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users
  resources :statuses do
   collection do
	get 'deleted'
	end
   member do
	get 'restore'
	end
   end

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  root :to => 'tickets#index'

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
 def index
    if current_user.admin?
	@statuses = Status.order('id').all
    else
      flash[:failure] = "Permission Denied!"
      redirect_to root_path
    end
  end


  def index
    if current_user.admin?
	@status = Status.order('id').all
    else
      flash[:failure] = "Permission Denied!"
      redirect_to root_path
    end
  end

  def show
    if current_user.admin?
	@status = Status.find(params[:id])
    else
      flash[:failure] = "Permission Denied!"
      redirect_to root_path
    end
  end

  def new
    if current_user.admin?
	@status =Status.new
    else
      flash[:failure] = "Permission Denied!"
      redirect_to root_path
    end
  end
  def create
    if current_user.admin?
	@status = Status.new(params[:status])
	if @status.save
		redirect_to(:action => 'index')
	else
		render('new')
	end
    else
      flash[:failure] = "Permission Denied!"
      redirect_to root_path
    end
  end
  def edit
    if current_user.admin?
	@status = Status.find(params[:id])
    else
      flash[:failure] = "Permission Denied!"
      redirect_to root_path
    end
  end
  def update
    if current_user.admin?
	@status = Status.find(params[:id])
	if @status.update_attributes(params[:status])
		redirect_to statuses_path(@statuses)
	else
		render('index')
	end
    else
      flash[:failure] = "Permission Denied!"
      redirect_to root_path
    end
  end
  def delete
    if current_user.admin?
	@status = Status.find(params[:id])
    else
      flash[:failure] = "Permission Denied!"
      redirect_to root_path
    end
  end
  def destroy
    if current_user.admin?
  	@status = Status.find(params[:id])
	@status.destroy
	redirect_to statuses_path
    else
      flash[:failure] = "Permission Denied!"
      redirect_to root_path
    end
  end
  def deleted
    if current_user.admin?
      @status = Status.only_deleted
      render('deleted')
    else
      flash[:failure] = "Permission Denied!"
      redirect_to root_path
    end
  end
  def restore
    if current_user.admin?
      Status.restore(params[:id])
      redirect_to deleted_statuses_path
    else
      flash[:failure] = "Permission Denied!"
      redirect_to root_path
    end
  end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/deleted.html.haml
= content_for(:title, "Archived Statuses")

.pure-u-1

 %table#statuses.pure-table.pure-table-bordered
  %thead
   %th  Restore
   %th  Name
  %tbody
  - @status.each do |status|
   %tr{:class => cycle('','pure-table-odd')}
    %td= link_to image_tag("add_button.png", :alt => "Restore Button" , size: "32x32", class:"table_button"), restore_status_path(status), :method => :get
    %td= status.name

app/views/statuses/edit.html.haml
=content_for(:title, "Edit Status")

.pure-u-1
 = form_tag status_path(@status), :method => :put, :class => "pure-form pure-form-stacked" do
  = label :status, :name, 'Status Name'
  = text_field :status, :name
  = submit_tag 'Save Changes', :class => "pure-button pure-button-primary"

app/views/statuses/index.html.haml
= content_for(:title, "Statuses")
= content_for(:extra, "The first item in this table is the default ticket status when a ticket is created")

.pure-u-1
 %p 
  = link_to image_tag("add_button.png", :alt => "Add Button", size: "32x32", class:"action_buttons"), new_status_path
 %p
  = link_to image_tag("archive_button.png", :alt => "Archive Button", size: "32x34", class:"archive_button"), deleted_statuses_path

 %table#statuses.pure-table.pure-table-bordered
  %thead
   %th  Edit
   %th  Delete
   %th  Name
  %tbody
  - @status.each do |status|
   %tr{:class => cycle('','pure-table-odd')}
    %td= link_to image_tag("edit_button.png", :alt => "Edit Button", size: "32x32", class:"table_button"), edit_status_path(status), :method => :get
    %td= link_to image_tag("delete_button.png", :alt => "Delete Button" , size: "32x32", class:"table_button"), status_path(status), :method => :delete
    %td= status.name

app/views/statuses/new.html.haml
= content_for(:title, "Create New Status")

.pure-u-1
 = form_tag statuses_path, :method => :post, :class => "pure-form pure-form-stacked" do
  = label :status, :name, 'Status Name'
  = text_field :status, :name
  = submit_tag 'Create Status', :class => "pure-button pure-button-success"