config/routes.rb
MhmrTroubleshooter::Application.routes.draw do
  resources :emails do
   collection do
	get 'deleted'
	end
   member do
	get 'restore'
	end
  end
  devise_for :users, :path_prefix => 'mhmr'
  resources :categories do
   collection do
	get 'deleted'
	end
   member do
	get 'restore'
   end
  end
  resources :tickets do
   collection do
	get 'summary'
	post 'summary'
	get 'monthSummary'
	end
  end
  resources :locations do
   collection do
	get 'deleted'
	end
   member do
	get 'restore'
	end
   end
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users
  resources :statuses do
   collection do
	get 'deleted'
	end
   member do
	get 'restore'
	end
   end

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  root :to => 'tickets#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
   has_many :tickets
   attr_accessible :name
   acts_as_paranoid
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    if current_user.admin?
	@categories = Category.order('name').all
    else
      flash[:failure] = "Permission Denied!"
      redirect_to root_path
    end
  end
  def show
    if current_user.admin?
	@category = Category.find(params[:id])
    else
      flash[:failure] = "Permission Denied!"
      redirect_to root_path
    end
  end

  def new
    if current_user.admin?
	@category =Category.new
    else
      flash[:failure] = "Permission Denied!"
      redirect_to root_path
    end
  end
  def create
    if current_user.admin?
	@category = Category.new(params[:category])
	if @category.save
		redirect_to(:action => 'index')
	else
		render('new')
	end
    else
      flash[:failure] = "Permission Denied!"
      redirect_to root_path
    end
  end
  def edit
    if current_user.admin?
	@category = Category.find(params[:id])
    else
      flash[:failure] = "Permission Denied!"
      redirect_to root_path
    end
  end
  def update
    if current_user.admin?
	@category = Category.find(params[:id])
	if @category.update_attributes(params[:category])
		redirect_to categories_path(@category)
	else
		render('index')
	end
    else
      flash[:failure] = "Permission Denied!"
      redirect_to root_path
    end
  end
  def delete
    if current_user.admin?
	@category = Category.find(params[:id])
    else
      flash[:failure] = "Permission Denied!"
      redirect_to root_path
    end
  end
  def destroy
    if current_user.admin?
  	@category = Category.find(params[:id])
	@category.destroy
	redirect_to categories_path
    else
      flash[:failure] = "Permission Denied!"
      redirect_to root_path
    end
  end
  def deleted
    if current_user.admin?
      @categories = Category.only_deleted
      render('deleted')
    else
      flash[:failure] = "Permission Denied!"
      redirect_to root_path
    end
  end
  def restore
    if current_user.admin?
      Category.restore(params[:id])
      redirect_to deleted_categories_path
    else
      flash[:failure] = "Permission Denied!"
      redirect_to root_path
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/delete.html.erb
<h1>Categories#delete</h1>
<p>Find me in app/views/categories/delete.html.erb</p>

app/views/categories/deleted.html.haml
= content_for(:title, "Archived Categories")

.pure-u-1

 %table#categories.pure-table.pure-table-bordered
  %thead
   %th  Restore
   %th  Name
  %tbody
  - @categories.each do |category|
   %tr{:class => cycle('','pure-table-odd')}
    %td= link_to image_tag("add_button.png", :alt => "Restore Button", size: "32x32", class:"table_button"), restore_category_path(category), :method => :get
    %td= category.name

app/views/categories/edit.html.haml
=content_for(:title, "Edit Categories")

.pure-u-1
 = form_tag category_path(@category), :method => :put, :class => "pure-form pure-form-stacked" do
  = label :category, :name, 'Category Name'
  = text_field :category, :name
  = submit_tag 'Save Changes', :class => "pure-button pure-button-primary"

app/views/categories/index.html.haml
= content_for(:title, "Categories")

.pure-u-1
 %p 
  = link_to image_tag("add_button.png", :alt => "Add Button", size: "32x32", class:"action_buttons"), new_category_path
 %p
  = link_to image_tag("archive_button.png", :alt => "Archive Button", size: "32x34", class:"archive_button"), deleted_categories_path

 %table#categories.pure-table.pure-table-bordered
  %thead
   %th  Edit
   %th  Delete
   %th  Name
  %tbody
  - @categories.each do |category|
   %tr{:class => cycle('','pure-table-odd')}
    %td= link_to image_tag("edit_button.png", :alt => "Edit Button", size: "32x32", class:"table_button"), edit_category_path(category), :method => :get
    %td= link_to image_tag("delete_button.png", :alt => "Delete Button" , size: "32x32", class:"table_button"), category_path(category), :method => :delete
    %td= category.name

app/views/categories/new.html.haml
= content_for(:title, "Create New Category")

.pure-u-1
 = form_tag categories_path, :method => :post, :class => "pure-form pure-form-stacked" do
  = label :category, :name, 'Category Name'
  = text_field :category, :name
  = submit_tag 'Create Category', :class => "pure-button pure-button-success"

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>