config/routes.rb
MhmrTroubleshooter::Application.routes.draw do
  resources :emails do
   collection do
	get 'deleted'
	end
   member do
	get 'restore'
	end
  end
  devise_for :users, :path_prefix => 'mhmr'
  resources :categories do
   collection do
	get 'deleted'
	end
   member do
	get 'restore'
   end
  end
  resources :tickets do
   collection do
	get 'summary'
	post 'summary'
	get 'monthSummary'
	end
  end
  resources :locations do
   collection do
	get 'deleted'
	end
   member do
	get 'restore'
	end
   end
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users
  resources :statuses do
   collection do
	get 'deleted'
	end
   member do
	get 'restore'
	end
   end

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  root :to => 'tickets#index'

end

app/views/layouts/application.html.haml
<!doctype html>
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %meta{:content => "MHMR-Troubleshooter System for ticket submission", :name => "description"}
    = favicon_link_tag 'favicon.ico'

    %title= yield(:title)
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags


  %body
    #layout
      / Menu toggle
      %a#menuLink.menu-link{:href => "#menu"}
        / Hamburger icon        
        %span
      #menu
        .pure-menu
          %a.pure-menu-heading{:href => "http://www.mhmrabv.org/"}= image_tag("mhmr_logo.png", :alt => "MHMR Logo", :height => "70px", :width =>"140")
          %ul.pure-menu-list
            %li.pure-menu-item
              = link_to "Tickets", tickets_path,{:class => "pure-menu-link"}      
            %li.pure-menu-item       
              = link_to "Users", users_path, {:class => "pure-menu-link"}
            %li.pure-menu-item
              = link_to "Emails", emails_path, {:class => "pure-menu-link"}
            %li.pure-menu-item
              = link_to "Categories", categories_path, {:class => "pure-menu-link"}
            %li.pure-menu-item
              = link_to "Locations", locations_path, {:class => "pure-menu-link"}
            %li.pure-menu-item
              = link_to "Statuses", statuses_path, {:class => "pure-menu-link"}
            %li.pure-menu-item
              = link_to "Reports", summary_tickets_path, {:class => "pure-menu-link"}
            %li.pure-menu-item
              = link_to "Log Out", destroy_user_session_path, {:class => "pure-menu-link", :method => :delete}
            
      #main
        - if flash[:failure]
          %div.notice{:id => "alert"}
            %a{:class => "alert", :href=> "#alert"}
              =flash[:failure]
        .header
          %h1= content_for?(:title) ? yield(:title) : "default title"
          %p= content_for?(:extra) ? yield(:extra) : ""
            
            
        .content
          %div
            = yield
        